version: '3.7'
services:
    mysql:
        image: mariadb:10.5
        # image: mysql:8.0 # 囲み文字を使用する場合
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation  
            TZ: "Asia/Tokyo"
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1 # for mariadb
        # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --performance-schema=false --expire_logs_days=1 --default-authentication-plugin=mysql_native_password # for myql
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    epgstation:
        build:
            context: "./epgstation"
            dockerfile: "debian.Dockerfile"
        volumes:
            - ./epgstation/config:/app/config
            - ./epgstation/data:/app/data
            - /var/tmp:/app/data/streamfiles
            # - /var/tmp:/app/data/upload
            - ./epgstation/thumbnail:/app/thumbnail
            - ./epgstation/logs:/app/logs
            - ./recorded:/app/recorded
            - ./join_logo_scp_trial/JL:/join_logo_scp_trial/JL
            - ./join_logo_scp_trial/logo:/join_logo_scp_trial/logo
            - ./join_logo_scp_trial/result:/join_logo_scp_trial/result
            - ./join_logo_scp_trial/setting:/join_logo_scp_trial/setting
            - ./join_logo_scp_trial/src:/join_logo_scp_trial/src 
        environment:
            TZ: "Asia/Tokyo"
        depends_on:
            - mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        # user: "1000:1000"
        devices:
            - /dev/vchiq:/dev/vchiq
            - /dev/video10:/dev/video10
            - /dev/video11:/dev/video11
            - /dev/video12:/dev/video12
            - /dev/video13:/dev/video13
            - /dev/video14:/dev/video14
            - /dev/video15:/dev/video15
            - /dev/video16:/dev/video16

        restart: always

volumes:
    mysql-db:
        driver: local

